### ISSUE TITLE
[Feature request] Documentation for the programmatic API

### ISSUE THREAD

**Issue by ilyazub** [chukhraiartur/seo-keyword-research-tool#1]
Currently, only CLI usage is documented in the README and demo.

`get_auto_complete`, `get_related_searches`, and `get_related_questions` can be imported but it's not documented in the README. For example, a web app can be build with the same functionality as the CLI.

https://github.com/chukhraiartur/seo-keyword-research-tool/blob/60a1f6f1f4ffa59ce26bb8782ddb265cab56cbb8/main.py#L135-L138

Wdyt?

**Comment by chukhraiartur** [comment]
@ilyazub I think this makes sense.  I'll start working on improvements soon.

Thanks for your issue 🙂
